# config/app.yml for rails-settings-cached
defaults: &defaults
  hobby: ['书法','绘画','象棋','麻将','摄影','音乐','插花','游泳','钓鱼','高尔夫','舞蹈','健身','茶道','桥牌','扑克','唱歌','跳舞','乒乓球','羽毛球','广场舞','太极拳','旅游','其他']
  speciality: ['太极','瑜伽','摄影','书法','乐器','桥牌','排舞','插花','编织','刺青','戏曲','武术','表演','其他']
  job: ['教师','会计师','律师','建筑师','医护人员','管理人员','财务/审计人员','顾问/咨询','公务员/事业单位','其他']
  skill_level: ['教授','副教授','工程师','高级工程师','经济师','高级经济师','会计师','高级会计师','注册会计师','其他']
  category: ['CT','体检报告','血常规','B超','其他']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
