# config/app.yml for rails-settings-cached
defaults: &defaults
  hobby: ['读书','书法','绘画','写作','唱歌','跳舞','乒乓球','羽毛球','广场舞','太极拳','旅游','跑步','下棋','其他']
  job: ['教师','医生','律师','工程师','企业家','公务员','职工','自由职业','其他']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
