# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
wechat_app_id: "wxd7dcf2bd4d9c9617"
wechat_secret: "744300d59f4334fecc57790d50c6da64"
wechat_token:  "wechat"
wechat_encoding_aes_key: "EncodingAESKey"
wechat_trusted_domain_fullname: "jkgl.ezu365.cn"
sms_api: 'http://www.jianzhou.sh.cn/JianzhouSMSWSServer/http/sendBatchMessage'
account: 'sdk_rongyikeji'
password:  'Rytech_123.com'
content_tag: '【e租365VIP】'