default: &default
  appid: "wx53eb0519112c5efc"
  secret: "bc127b0fbc1e366ef11fc4c24b539867"
  token:    "peterfei"
  access_token: "/var/tmp/wechat_access_token"
development:
  <<: *default
  # trusted_domain_fullname: "http://wechatdo.ngrok.cc"

test:
  <<: *default

